### ISSUE TITLE
Investigate stripe multi-account creation

### ISSUE THREAD

**Issue by azoff** [omniprojects/omni-stripe-php-client#4]
It appears that [David Shea](https://omniprojects.cloudforce.com/001o000000ZA016AAD) created multiple stripe accounts this morning by going through the marketing funnel. These are the four accounts he created:

1) https://manage.stripe.com/customers/cus_6el2aRgQXojD8a

2) https://manage.stripe.com/customers/cus_6el397C208ocar

3) https://manage.stripe.com/customers/cus_6el4gPnUu8oPtT

4) https://manage.stripe.com/customers/cus_6el5rMtAcPNS3g

Each account was created as a result of subsequent calls to the `/profile` update API call. Is it possible that the stripe account creation trigger fires every time an account is updated?

**Comment by dmitrymomot** [comment]
@azoff, no, trigger must fires only when an account is created.
But I couldn't reproduce this bug, I tried a few times.

**Comment by dmitrymomot** [comment]
@dkirichenko, could you check in what case SF can request stripe create method on API?
